In [8]:
import numpy as np

In [3]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
a[2]

np.int64(4)

In [5]:
a.dtype

dtype('int64')

In [6]:
a.shape

(3,)

In [10]:
b=np.array([(1,2),(3,4),(5,6)])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
b[1,1]

np.int64(4)

In [12]:
b[0:2,1]

array([2, 4])

In [13]:
b.ndim

2

In [14]:
b.shape

(3, 2)

In [16]:
np.reshape(b,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.reshape(b,(1,-1))

array([[1, 2, 3, 4, 5, 6]])

In [23]:
np.reshape(b,(-1,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])