In [8]:
import numpy as np

In [3]:
a=np.array([2,3,4])
a

array([2, 3, 4])

In [4]:
a[2]

np.int64(4)

In [5]:
a.dtype

dtype('int64')

In [6]:
a.shape

(3,)

In [10]:
b=np.array([(1,2),(3,4),(5,6)])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
b[1,1]

np.int64(4)

In [12]:
b[0:2,1]

array([2, 4])

In [13]:
b.ndim

2

In [14]:
b.shape

(3, 2)

In [16]:
np.reshape(b,(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.reshape(b,(1,-1))

array([[1, 2, 3, 4, 5, 6]])

In [23]:
np.reshape(b,(-1,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [25]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [27]:
np.arange(5,10,step=2)

array([5, 7, 9])

In [28]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
np.linspace(1,9,num=3)

array([1., 5., 9.])

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.ones(4)

array([1., 1., 1., 1.])

In [33]:
np.empty(3)

array([1., 5., 9.])

In [34]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])